import React, { useState, useEffect } from "react";

import { Loader, Card, FormField } from "../components";
import { Post, Posts } from "../types/interfaces";

const RenderCards = ({ data, title }: Posts) => {
	if (data?.length > 0) {
		return (
			<>
				{data.map((post) => (
					<Card key={post._id} {...post} />
				))}
			</>
		);
	}

	return (
		<h2 className="mt-5 font-bold text-primary text-xl uppercase">{title}</h2>
	);
};

const Home = () => {
	const [loading, setLoading] = useState(false);
	const [allPosts, setAllPosts] = useState<[]>([]);

	const [searchText, setSearchText] = useState("");
	const [searchResults, setSearchResults] = useState<any>([]);
	const [searchTimeout, setSearchTimeout] = useState<any>(null);

	useEffect(() => {
		const fetchPosts = async () => {
			setLoading(true);
			try {
				const response = await fetch("http://localhost:8080/api/v1/post", {
					method: "GET",
					headers: {
						"Content-Type": "application/json",
					},
				});

				if (response.ok) {
					const result = await response.json();
					setAllPosts(result.data.reverse());
				}
			} catch (error) {
				alert(error);
			} finally {
				setLoading(false);
			}
		};

		fetchPosts();
	}, []);

	const handleSearch = (e: React.ChangeEvent<HTMLInputElement>) => {
		clearTimeout(searchTimeout);
		setSearchText(e.target.value);

		setSearchTimeout(
			setTimeout(() => {
				const filterResults = allPosts.filter((post: Post) => {
					return (
						post.name.toLowerCase().includes(searchText.toLowerCase()) ||
						post.prompt.toLowerCase().includes(searchText.toLowerCase())
					);
				});

				setSearchResults(filterResults);
			}, 300)
		);
	};

	return (
		<div>
			<section className="max-w-7xl mx-auto">
				<div>
					<h1 className="font-extrabold text-dark text-[2rem]">
						The Community Showcase
					</h1>
					<p className="mt-2 text-dark text-lg">
						Browse through a collection of dreamful and stunning images
						generated by Dall-E AI.
					</p>
				</div>

				<div className="mt-8">
					<FormField
						labelName="Search"
						type="text"
						name="text"
						placeholder="Start typing here to filter posts"
						value={searchText}
						handleChange={handleSearch}
					/>
				</div>

				<div className="mt-4">
					{loading ? (
						<div className="flex justify-center items-center">
							<Loader />
						</div>
					) : (
						<>
							<div className="h-10">
								{searchText && (
									<h2 className="font-medium text-dark text-xl mb-3">
										Showing results for{" "}
										<span className="text-dark">{searchText}</span>
									</h2>
								)}
							</div>
							<div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
								{searchText ? (
									<RenderCards
										data={searchResults}
										title="No search results found"
									/>
								) : (
									<RenderCards data={allPosts} title="No posts found" />
								)}
							</div>
						</>
					)}
				</div>
			</section>
		</div>
	);
};

export default Home;
